name: "Terraform CI/CD"

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - ".gitignore"

  pull_request:
    paths-ignore:
      - "**.md"
      - ".gitignore"

jobs:
  # This job runs CI checks on all pushes and PRs.
  ci_checks:
    name: "Terraform CI Checks"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{secrets.HCP_API_TOKEN}}

      - name: "Terraform Format Check"
        id: fmt
        run: terraform fmt -check -recursive

      - name: "Terraform Init"
        id: init
        run: terraform init

      - name: "Terraform Validate"
        id: validate
        run: terraform validate

  # This job triggers the HCP run, but ONLY on a push to the main branch.
  trigger_hcp_run:
    name: "Trigger HCP Deployment"
    needs: [ci_checks] # This job depends on the CI checks passing
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Check For Existing Runs"
        id: check-runs
        env:
          TF_API_TOKEN: ${{secrets.HCP_API_TOKEN}}
          TF_CLOUD_ORGANIZATION: "sweepstack-alpha"
          TF_WORKSPACE_NAME: "sweepstack-oidc-management"
        run: |
          WORKSPACE_ID=$(curl -s -H "Authorization: Bearer $TF_API_TOKEN" \
            "https://api.hashicorp.cloud/api/v2/organizations/$TF_CLOUD_ORGANIZATION/workspaces/$TF_WORKSPACE_NAME" | jq -r '.data.id')
          RUN_COUNT=$(curl -s -H "Authorization: Bearer $TF_API_TOKEN" \
            "https://api.hashicorp.cloud/api/v2/workspaces/$WORKSPACE_ID/runs" | jq -r '.data | length')
          echo "Found $RUN_COUNT runs in the workspace $TF_WORKSPACE_NAME"
          echo "run_count=$RUN_COUNT" >> $GITHUB_OUTPUT

      - name: "Upload Configuration"
        if: steps.check-runs.outputs.run_count == '0'
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.3.2
        with:
          workspace: ${{env.TF_WORKSPACE_NAME}}
          directory: "/terraform"

      - name: "Create Terraform Run"
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
        with:
          workspace: ${{env.TF_WORKSPACE_NAME}}
          message: ${{github.event.head_commit.message}} # This uses the GH commit as the HCP run subject
